/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_smart_bulkingupdate_BulkingPatch */

#ifndef _Included_com_smart_bulkingupdate_BulkingPatch
#define _Included_com_smart_bulkingupdate_BulkingPatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_smart_bulkingupdate_BulkingPatch
 * Method:    generateBulkingPatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_smart_bulkingupdate_BulkingPatch_generateBulkingPatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_smart_bulkingupdate_BulkingPatch
 * Method:    mergeBulkingPatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_smart_bulkingupdate_BulkingPatch_mergeBulkingPatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
